export const MEALS_BY_CATEGORY = {
  "Main Course": [
    {
      id: "1",
      name: "Nasi Lemak",
      description: "Fragrant coconut rice with sambal, anchovies, and egg",
      price: 6.5,
      category: "Main Course",
      calories: 450,
      image: "/nasi-lemak.jpg",
    },
    {
      id: "2",
      name: "Chicken Rice",
      description: "Succulent steamed chicken with aromatic rice",
      price: 7.0,
      category: "Main Course",
      calories: 520,
      image: "/chicken-rice.jpg",
    },
    {
      id: "3",
      name: "Beef Rendang",
      description: "Tender beef cooked in rich coconut and spice curry",
      price: 8.5,
      category: "Main Course",
      calories: 580,
      image: "/beef-rendang.jpg",
    },
    {
      id: "4",
      name: "Fish Curry Rice",
      description: "White fish in aromatic yellow curry with rice",
      price: 7.5,
      category: "Main Course",
      calories: 480,
      image: "/fish-curry-rice.jpg",
    },
  ],
  Sides: [
    {
      id: "5",
      name: "Fried Vegetables",
      description: "Fresh seasonal vegetables lightly fried",
      price: 3.5,
      category: "Sides",
      calories: 180,
      image: "/fried-vegetables.jpg",
    },
    {
      id: "6",
      name: "Spring Rolls",
      description: "Crispy golden spring rolls (3 pieces)",
      price: 4.0,
      category: "Sides",
      calories: 220,
      image: "/fresh-spring-rolls.png",
    },
    {
      id: "7",
      name: "Roti Canai",
      description: "Flaky Indian bread with curry dip",
      price: 3.0,
      category: "Sides",
      calories: 280,
      image: "/roti-canai.jpg",
    },
  ],
  Desserts: [
    {
      id: "8",
      name: "Chocolate Cake",
      description: "Rich and moist chocolate cake slice",
      price: 4.5,
      category: "Desserts",
      calories: 350,
      image: "/decadent-chocolate-cake.png",
    },
    {
      id: "9",
      name: "Tropical Fruit Salad",
      description: "Fresh mango, papaya, and pineapple",
      price: 5.0,
      category: "Desserts",
      calories: 120,
      image: "/colorful-fruit-salad.png",
    },
  ],
  Beverages: [
    {
      id: "10",
      name: "Iced Milo",
      description: "Refreshing cold chocolate malt drink",
      price: 2.5,
      category: "Beverages",
      calories: 150,
      image: "/iced-milo.jpg",
    },
    {
      id: "11",
      name: "Fresh Orange Juice",
      description: "Freshly squeezed orange juice",
      price: 3.0,
      category: "Beverages",
      calories: 110,
      image: "/glass-of-orange-juice.png",
    },
  ],
}
