export const MEALS_BY_CATEGORY = {
  "Coffee": [
    {
      id: "1",
      name: "Espresso",
      description: "Bold and concentrated coffee shot",
      price: 6.0,
      category: "Coffee",
      calories: 10,
      image: "/espresso-shot.png",
    },
    {
      id: "2",
      name: "Americano",
      description: "Espresso with hot water",
      price: 6.0,
      category: "Coffee",
      calories: 15,
      image: "/americano-coffee.png",
    },
    {
      id: "3",
      name: "Latte",
      description: "Espresso with steamed milk",
      price: 6.0,
      category: "Coffee",
      calories: 120,
      image: "/latte-art.png",
    },
    {
      id: "4",
      name: "Cappuccino",
      description: "Espresso with equal parts steamed milk and foam",
      price: 6.0,
      category: "Coffee",
      calories: 100,
      image: "/frothy-cappuccino.png",
    },
    {
      id: "5",
      name: "Flatwhite",
      description: "Espresso with velvety microfoam",
      price: 6.0,
      category: "Coffee",
      calories: 120,
      image: "/flatwhite.jpg",
    },
  ],
  "Flavoured Coffee": [
    {
      id: "6",
      name: "Mocha",
      description: "Espresso with chocolate and milk (Hot/Cold)",
      price: 9.5,
      category: "Flavoured Coffee",
      calories: 200,
      image: "/rich-mocha.png",
    },
    {
      id: "7",
      name: "Caramel",
      description: "Smooth caramel coffee (Hot/Cold)",
      price: 9.5,
      category: "Flavoured Coffee",
      calories: 210,
      image: "/caramel-coffee.jpg",
    },
    {
      id: "8",
      name: "Salted Caramel",
      description: "Sweet caramel with a hint of salt (Hot/Cold)",
      price: 9.5,
      category: "Flavoured Coffee",
      calories: 220,
      image: "/salted-caramel-coffee.jpg",
    },
    {
      id: "9",
      name: "Vanilla",
      description: "Aromatic vanilla-infused coffee (Hot/Cold)",
      price: 9.5,
      category: "Flavoured Coffee",
      calories: 190,
      image: "/vanilla-coffee.jpg",
    },
    {
      id: "10",
      name: "Banana",
      description: "Creamy banana-flavored coffee (Hot/Cold)",
      price: 9.5,
      category: "Flavoured Coffee",
      calories: 210,
      image: "/banana-coffee.jpg",
    },
  ],
  "Non Coffee": [
    {
      id: "11",
      name: "Chocolate",
      description: "Rich hot or cold chocolate drink",
      price: 9.5,
      category: "Non Coffee",
      calories: 240,
      image: "/chocolate-drink.jpg",
    },
    {
      id: "12",
      name: "Matcha",
      description: "Traditional matcha tea (Hot/Cold)",
      price: 9.5,
      category: "Non Coffee",
      calories: 80,
      image: "/matcha.jpg",
    },
  ],
  "Ice Blended": [
    {
      id: "13",
      name: "Cookies & Cream",
      description: "Blended ice drink with cookies and cream",
      price: 13.0,
      category: "Ice Blended",
      calories: 320,
      image: "/cookies-cream-blended.jpg",
    },
    {
      id: "14",
      name: "Banana Chocolate",
      description: "Blended banana and chocolate ice drink",
      price: 13.0,
      category: "Ice Blended",
      calories: 310,
      image: "/banana-chocolate-blended.jpg",
    },
    {
      id: "15",
      name: "Salted Caramel",
      description: "Blended salted caramel ice drink",
      price: 13.0,
      category: "Ice Blended",
      calories: 300,
      image: "/salted-caramel-blended.jpg",
    },
  ],
  "Sandwiches": [
    {
      id: "16",
      name: "Chicken BBQ",
      description: "Grilled chicken with BBQ sauce",
      price: 9.5,
      category: "Sandwiches",
      calories: 450,
      image: "/bbq-chicken-sandwich.jpg",
    },
    {
      id: "17",
      name: "Baked Honey Chicken",
      description: "Tender baked chicken with honey glaze",
      price: 9.5,
      category: "Sandwiches",
      calories: 480,
      image: "/honey-chicken-sandwich.jpg",
    },
    {
      id: "18",
      name: "Coney Island",
      description: "Classic Coney Island sandwich",
      price: 9.5,
      category: "Sandwiches",
      calories: 520,
      image: "/coney-island-sandwich.jpg",
    },
    {
      id: "19",
      name: "Black Pepper Chicken",
      description: "Spicy black pepper chicken sandwich",
      price: 9.5,
      category: "Sandwiches",
      calories: 470,
      image: "/black-pepper-chicken.jpg",
    },
    {
      id: "20",
      name: "Smoked Chicken & Cheese Sandwich Meltz",
      description: "Smoked chicken with melted cheese",
      price: 9.5,
      category: "Sandwiches",
      calories: 540,
      image: "/smoked-chicken-cheese.jpg",
    },
    {
      id: "21",
      name: "Dakgalbi Chicken Meltz",
      description: "Korean-style spicy chicken with melted cheese",
      price: 9.5,
      category: "Sandwiches",
      calories: 530,
      image: "/dakgalbi-chicken.jpg",
    },
    {
      id: "22",
      name: "Ham & Cheese",
      description: "Classic ham and cheese sandwich",
      price: 7.0,
      category: "Sandwiches",
      calories: 380,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "23",
      name: "Tuna Mentai Mayo",
      description: "Tuna with spicy mentai mayo",
      price: 7.0,
      category: "Sandwiches",
      calories: 420,
      image: "/placeholder.svg?height=300&width=300",
    },
  ],
  "Hot Meals": [
    {
      id: "24",
      name: "Korean Mac N Cheese",
      description: "Korean-style creamy mac and cheese",
      price: 8.5,
      category: "Hot Meals",
      calories: 480,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "25",
      name: "Buttermilk Mac N Cheese",
      description: "Creamy buttermilk mac and cheese",
      price: 8.5,
      category: "Hot Meals",
      calories: 520,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "26",
      name: "Baked Mac N Cheese",
      description: "Baked creamy mac and cheese with breadcrumbs",
      price: 8.5,
      category: "Hot Meals",
      calories: 550,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "27",
      name: "Chicken Lasagna",
      description: "Layered chicken lasagna with cheese",
      price: 8.5,
      category: "Hot Meals",
      calories: 580,
      image: "/placeholder.svg?height=300&width=300",
    },
  ],
  "Pasta": [
    {
      id: "28",
      name: "Chicken Meatball",
      description: "Pasta with chicken meatballs in tomato sauce",
      price: 10.5,
      category: "Pasta",
      calories: 520,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "29",
      name: "Spaghetti Carbonara",
      description: "Classic carbonara with bacon and parmesan",
      price: 10.5,
      category: "Pasta",
      calories: 580,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "30",
      name: "Spaghetti Bolognese",
      description: "Spaghetti with rich meat sauce",
      price: 10.5,
      category: "Pasta",
      calories: 540,
      image: "/placeholder.svg?height=300&width=300",
    },
  ],
  "Ready To Eat Meals": [
    {
      id: "31",
      name: "Spicy Korean Noodles with Crabmeat & Egg",
      description: "Spicy Korean noodles topped with crabmeat stick and egg",
      price: 13.0,
      category: "Ready To Eat Meals",
      calories: 520,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "32",
      name: "Mapo Tofu On Rice",
      description: "Spicy tofu in Sichuan sauce on fluffy rice",
      price: 13.0,
      category: "Ready To Eat Meals",
      calories: 480,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "33",
      name: "Chili Chicken With Rice",
      description: "Spicy chili chicken served with rice",
      price: 12.5,
      category: "Ready To Eat Meals",
      calories: 550,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "34",
      name: "Black Pepper Chicken With Rice",
      description: "Black pepper chicken served with rice",
      price: 12.5,
      category: "Ready To Eat Meals",
      calories: 520,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "35",
      name: "Karage Chicken Bento",
      description: "Japanese fried chicken bento with rice",
      price: 15.9,
      category: "Ready To Eat Meals",
      calories: 620,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "36",
      name: "Dried Tomyum Chicken",
      description: "Thai tom yum chicken with rice",
      price: 12.5,
      category: "Ready To Eat Meals",
      calories: 500,
      image: "/placeholder.svg?height=300&width=300",
    },
  ],
  "Cup Dessert": [
    {
      id: "37",
      name: "German Chocolate Mousse",
      description: "Rich German chocolate mousse in a cup",
      price: 5.5,
      category: "Cup Dessert",
      calories: 280,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "38",
      name: "Tiramisu Mousse",
      description: "Classic tiramisu-flavored mousse",
      price: 5.5,
      category: "Cup Dessert",
      calories: 260,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "39",
      name: "Biscoff Mousse",
      description: "Creamy Biscoff cookie mousse",
      price: 5.5,
      category: "Cup Dessert",
      calories: 270,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "40",
      name: "Strawberry Crumble",
      description: "Strawberry mousse with crumble topping",
      price: 5.5,
      category: "Cup Dessert",
      calories: 240,
      image: "/placeholder.svg?height=300&width=300",
    },
  ],
  "Muffins": [
    {
      id: "41",
      name: "Red Velvet Muffin",
      description: "Classic red velvet muffin",
      price: 7.0,
      category: "Muffins",
      calories: 340,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "42",
      name: "Double Chocolate Muffin",
      description: "Rich double chocolate muffin",
      price: 7.0,
      category: "Muffins",
      calories: 380,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "43",
      name: "Blueberry Muffin",
      description: "Fresh blueberry muffin",
      price: 7.0,
      category: "Muffins",
      calories: 320,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "44",
      name: "Banana Chocolate Chip Muffin",
      description: "Banana muffin loaded with chocolate chips",
      price: 7.0,
      category: "Muffins",
      calories: 360,
      image: "/placeholder.svg?height=300&width=300",
    },
  ],
  "Others": [
    {
      id: "45",
      name: "Salted Salmon Onigiri",
      description: "Japanese rice ball with salted salmon",
      price: 7.0,
      category: "Others",
      calories: 280,
      image: "/placeholder.svg?height=300&width=300",
    },
  ],
  "Fuzz Drink": [
    {
      id: "46",
      name: "Watermelon Mango",
      description: "Refreshing watermelon and mango drink",
      price: 9.0,
      category: "Fuzz Drink",
      calories: 140,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "47",
      name: "Kiwi Strawberry",
      description: "Tropical kiwi and strawberry drink",
      price: 9.0,
      category: "Fuzz Drink",
      calories: 130,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "48",
      name: "Apple Buzz",
      description: "Crisp apple-flavored buzz drink",
      price: 9.0,
      category: "Fuzz Drink",
      calories: 120,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "49",
      name: "Apple Strawberry",
      description: "Blend of apple and strawberry",
      price: 9.0,
      category: "Fuzz Drink",
      calories: 125,
      image: "/placeholder.svg?height=300&width=300",
    },
  ],
  "Flavoured Tea": [
    {
      id: "50",
      name: "Peach Tea",
      description: "Smooth peach-flavored tea (Hot/Cold)",
      price: 7.0,
      category: "Flavoured Tea",
      calories: 60,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "51",
      name: "Lemonlime Tea",
      description: "Zesty lemon and lime tea (Hot/Cold)",
      price: 7.0,
      category: "Flavoured Tea",
      calories: 50,
      image: "/placeholder.svg?height=300&width=300",
    },
  ],
  "Tea": [
    {
      id: "52",
      name: "Earl Grey Tea",
      description: "Classic Earl Grey tea (Hot/Cold)",
      price: 5.0,
      category: "Tea",
      calories: 0,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "53",
      name: "English Breakfast Tea",
      description: "Traditional English breakfast tea (Hot/Cold)",
      price: 5.0,
      category: "Tea",
      calories: 0,
      image: "/placeholder.svg?height=300&width=300",
    },
  ],
  "Thai Drink": [
    {
      id: "54",
      name: "Butterfly Pea",
      description: "Beautiful butterfly pea flower drink",
      price: 8.0,
      category: "Thai Drink",
      calories: 40,
      image: "/placeholder.svg?height=300&width=300",
    },
    {
      id: "55",
      name: "Thai Tea",
      description: "Traditional Thai iced tea",
      price: 8.0,
      category: "Thai Drink",
      calories: 180,
      image: "/placeholder.svg?height=300&width=300",
    },
  ],
}
